name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v7

    - name: Install build dependencies
      run: brew install ninja

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        host: 'mac'
        target: 'desktop'
        arch: 'clang_64'
        modules: 'qt5compat'      # 提供 Core5Compat

    - name: Configure CMake
      run: cmake -B build -S . -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Run unit tests
      run: ctest --test-dir build --output-on-failure
