name: Build Windows
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        # QtNetwork is included in the base installation for desktop
        install-deps: 'true'
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 ..
        cmake --build . --config Release
    - name: Package
      run: |
        cd build/src/Release
        windeployqt AlexCode.exe
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AlexCode-Windows-AI
        path: build/src/Release/
